### ISSUE TITLE
Run gin.exe commands with full path to avoid using globally installed binaries

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/WinGIN#143]
Came across this on my dev VM where I have a `gin.exe` in my `%PATH%`.  WinGIN was calling `gin.exe` and it was using that (outdated) binary instead of the one it installs itself.

Perhaps a bit of an edge case, but it would be good to avoid this.

**Comment by JiriVanek** [comment]
path to gin.exe in cmd in GinRepository.cs GetCommandLineOutputEvent causes problems... needs further investigation
