### ISSUE TITLE
Specify list of supported Dokan app versions

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/WinGIN#160]
https://github.com/G-Node/WinGIN/blob/20be0ca7927ed6f06b103cc8f1b8605b66a6804f/GinClientApp/Program.cs#L105

If we plan on supporting multiple versions in general, we might consider having an array of versions to check through and make this a bit more elegant.
For example:
```cs
if (!CheckInstalledAny(dokanAppVersions)) {
...
```

**Comment by JiriVanek** [comment]
the idea is support only latest version... or tested version. In dokan update from version 1.2.xxx to 1.3.xx was API change so I was forced to make the check and force users to update Dokan. Basically I presume that users are using dokan that is bundled in WinGIN installer so the version check is to verify that user installed right version.
But I will add the information about supported version in error message so user will know that current version is "unsupported"

**Comment by achilleas-k** [comment]
Ok.  Good plan.  Closing.
