### ISSUE TITLE
Notice for gin-cli download and extraction during installation

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/WinGIN#81]
During installation, the progress bar stops around 60% to download and extract gin-cli. This can take minutes, depending on bandwidth and extraction speed. Some information for the user would be good to let them know what is happening and that the installer isn't frozen.

**Comment by The-E** [comment]
This is easily doable, but requires implementation of a downloader for gin-cli specifically.

My preferred solution would be to (and this also kinda applies to issue #82) to move these two steps out of the installer and make them part of the startup process for the UI client; The installer would finish by launching the GinClientApp, which would then download and install Dokan and gin-cli
